### ISSUE TITLE
the point3d.obj generated by NeuS2 is empty

### ISSUE THREAD

**Issue by danyingwind** [AuthorityWang/VideoGS#8]
Hi, thank you for your great work!

I run train_sequence.py using the HiFi4G dataset, and I got an empty points3d.obj with zero vertex.

According to other closed issues, I rebuild the NeuS2_K but I still got an empty points3d.obj.
The error log is like:
```
Error encountered while loading file:
"points3d.obj"

Error details: No vertex found
```

Could you please help me deal with this problem? Thank you 

Here are some information about my platform:
```
cmake version 3.22.1
Cuda compilation tools, release 11.7, V11.7.99
```

Here are some information about my conda:

```
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                       2_gnu    conda-forge
absl-py                   2.1.0                    pypi_0    pypi
addict                    2.4.0                    pypi_0    pypi
aom                       3.5.0                h27087fc_0    conda-forge
asttokens                 3.0.0                    pypi_0    pypi
attrs                     24.3.0                   pypi_0    pypi
blas                      1.0                         mkl    conda-forge
blinker                   1.9.0                    pypi_0    pypi
brotli-python             1.1.0            py39hf88036b_2    conda-forge
bzip2                     1.0.8                h4bc722e_7    conda-forge
ca-certificates           2024.12.14           hbcca054_0    conda-forge
cairo                     1.16.0            h35add3b_1015    conda-forge
certifi                   2024.12.14         pyhd8ed1ab_0    conda-forge
cffi                      1.17.1           py39h15c3d72_0    conda-forge
charset-normalizer        3.4.0              pyhd8ed1ab_1    conda-forge
click                     8.1.7                    pypi_0    pypi
comm                      0.2.2                    pypi_0    pypi
commentjson               0.9.0                    pypi_0    pypi
configargparse            1.7                      pypi_0    pypi
contourpy                 1.3.0                    pypi_0    pypi
cuda-cudart               11.7.99                       0    nvidia
cuda-cupti                11.7.101                      0    nvidia
cuda-libraries            11.7.1                        0    nvidia
cuda-nvrtc                11.7.99                       0    nvidia
cuda-nvtx                 11.7.91                       0    nvidia
cuda-runtime              11.7.1                        0    nvidia
cuda-version              12.6                          3    nvidia
cycler                    0.12.1                   pypi_0    pypi
dash                      2.18.2                   pypi_0    pypi
dash-core-components      2.0.0                    pypi_0    pypi
dash-html-components      2.0.0                    pypi_0    pypi
dash-table                5.0.0                    pypi_0    pypi
dav1d                     1.2.1                hd590300_0    conda-forge
decorator                 5.1.1                    pypi_0    pypi
exceptiongroup            1.2.2                    pypi_0    pypi
executing                 2.1.0                    pypi_0    pypi
fastjsonschema            2.21.1                   pypi_0    pypi
ffmpeg                    6.0.0           gpl_hdbbbd96_103    conda-forge
flask                     3.0.3                    pypi_0    pypi
font-ttf-dejavu-sans-mono 2.37                 hab24e00_0    conda-forge
font-ttf-inconsolata      3.000                h77eed37_0    conda-forge
font-ttf-source-code-pro  2.038                h77eed37_0    conda-forge
font-ttf-ubuntu           0.83                 h77eed37_3    conda-forge
fontconfig                2.15.0               h7e30c49_1    conda-forge
fonts-conda-ecosystem     1                             0    conda-forge
fonts-conda-forge         1                             0    conda-forge
fonttools                 4.55.3                   pypi_0    pypi
freetype                  2.12.1               h267a509_2    conda-forge
fribidi                   1.0.10               h36c2ea0_0    conda-forge
gettext                   0.22.5               he02047a_3    conda-forge
gettext-tools             0.22.5               he02047a_3    conda-forge
gmp                       6.3.0                hac33072_2    conda-forge
gnutls                    3.7.9                hb077bed_0    conda-forge
graphite2                 1.3.13            h59595ed_1003    conda-forge
grpcio                    1.68.1                   pypi_0    pypi
h2                        4.1.0              pyhd8ed1ab_1    conda-forge
harfbuzz                  7.3.0                hdb3a94d_0    conda-forge
hpack                     4.0.0              pyhd8ed1ab_1    conda-forge
hyperframe                6.0.1              pyhd8ed1ab_1    conda-forge
icu                       72.1                 hcb278e6_0    conda-forge
idna                      3.10               pyhd8ed1ab_1    conda-forge
imageio                   2.16.2                   pypi_0    pypi
importlib-metadata        8.5.0                    pypi_0    pypi
importlib-resources       6.4.5                    pypi_0    pypi
intel-openmp              2022.0.1          h06a4308_3633    defaults
ipython                   8.18.1                   pypi_0    pypi
ipywidgets                8.1.5                    pypi_0    pypi
itsdangerous              2.2.0                    pypi_0    pypi
jedi                      0.19.2                   pypi_0    pypi
jinja2                    3.1.4                    pypi_0    pypi
joblib                    1.4.2                    pypi_0    pypi
jpeg                      9e                   h0b41bf4_3    conda-forge
jsonschema                4.23.0                   pypi_0    pypi
jsonschema-specifications 2024.10.1                pypi_0    pypi
jupyter-core              5.7.2                    pypi_0    pypi
jupyterlab-widgets        3.0.13                   pypi_0    pypi
kiwisolver                1.4.7                    pypi_0    pypi
lame                      3.100             h166bdaf_1003    conda-forge
lark-parser               0.7.8                    pypi_0    pypi
lcms2                     2.15                 hfd0df8a_0    conda-forge
ld_impl_linux-64          2.43                 h712a8e2_2    conda-forge
lerc                      4.0.0                h27087fc_0    conda-forge
libasprintf               0.22.5               he8f35ee_3    conda-forge
libasprintf-devel         0.22.5               he8f35ee_3    conda-forge
libass                    0.17.1               hc9aadba_0    conda-forge
libblas                   3.9.0            16_linux64_mkl    conda-forge
libcblas                  3.9.0            16_linux64_mkl    conda-forge
libcublas                 11.10.3.66                    0    nvidia
libcufft                  10.7.2.124           h4fbf590_0    nvidia
libcufile                 1.11.1.6                      0    nvidia
libcurand                 10.3.7.77                     0    nvidia
libcusolver               11.4.0.1                      0    nvidia
libcusparse               11.7.4.91                     0    nvidia
libdeflate                1.17                 h0b41bf4_0    conda-forge
libdrm                    2.4.124              hb9d3cd8_0    conda-forge
libexpat                  2.6.4                h5888daf_0    conda-forge
libffi                    3.4.2                h7f98852_5    conda-forge
libgcc                    14.2.0               h77fa898_1    conda-forge
libgcc-ng                 14.2.0               h69a702a_1    conda-forge
libgettextpo              0.22.5               he02047a_3    conda-forge
libgettextpo-devel        0.22.5               he02047a_3    conda-forge
libglib                   2.82.2               h2ff4ddf_0    conda-forge
libgomp                   14.2.0               h77fa898_1    conda-forge
libiconv                  1.17                 hd590300_2    conda-forge
libidn2                   2.3.7                hd590300_0    conda-forge
liblapack                 3.9.0            16_linux64_mkl    conda-forge
liblzma                   5.6.3                hb9d3cd8_1    conda-forge
liblzma-devel             5.6.3                hb9d3cd8_1    conda-forge
libnpp                    11.7.4.75                     0    nvidia
libnsl                    2.0.1                hd590300_0    conda-forge
libnvjpeg                 11.8.0.2                      0    nvidia
libopus                   1.3.1                h7f98852_1    conda-forge
libpciaccess              0.18                 hd590300_0    conda-forge
libpng                    1.6.44               hadc24fc_0    conda-forge
libsqlite                 3.47.2               hee588c1_0    conda-forge
libstdcxx                 14.2.0               hc0a3c3a_1    conda-forge
libstdcxx-ng              14.2.0               h4852527_1    conda-forge
libtasn1                  4.19.0               h166bdaf_0    conda-forge
libtiff                   4.5.0                h6adf6a1_2    conda-forge
libunistring              0.9.10               h7f98852_0    conda-forge
libuuid                   2.38.1               h0b41bf4_0    conda-forge
libva                     2.18.0               h0b41bf4_0    conda-forge
libvpx                    1.13.1               h59595ed_0    conda-forge
libwebp-base              1.4.0                hd590300_0    conda-forge
libxcb                    1.13              h7f98852_1004    conda-forge
libxcrypt                 4.4.36               hd590300_1    conda-forge
libxml2                   2.11.5               h0d562d8_0    conda-forge
libzlib                   1.3.1                hb9d3cd8_2    conda-forge
markdown                  3.7                      pypi_0    pypi
markupsafe                3.0.2                    pypi_0    pypi
matplotlib                3.9.4                    pypi_0    pypi
matplotlib-inline         0.1.7                    pypi_0    pypi
mkl                       2022.1.0           hc2b9512_224    defaults
nbformat                  5.10.4                   pypi_0    pypi
ncurses                   6.5                  he02047a_1    conda-forge
nest-asyncio              1.6.0                    pypi_0    pypi
nettle                    3.9.1                h7ab15ed_0    conda-forge
numpy                     2.0.2            py39h9cb892a_1    conda-forge
open3d                    0.18.0                   pypi_0    pypi
opencv-python             4.5.5.64                 pypi_0    pypi
openh264                  2.3.1                hcb278e6_2    conda-forge
openjpeg                  2.5.0                hfec8fc6_2    conda-forge
openssl                   3.4.0                hb9d3cd8_0    conda-forge
p11-kit                   0.24.1               hc5aa10d_0    conda-forge
packaging                 24.2                     pypi_0    pypi
pandas                    2.2.3                    pypi_0    pypi
parso                     0.8.4                    pypi_0    pypi
pcre2                     10.44                hba22ea6_2    conda-forge
pexpect                   4.9.0                    pypi_0    pypi
pillow                    9.4.0            py39h2320bf1_1    conda-forge
pip                       24.3.1             pyh8b19718_2    conda-forge
pixman                    0.44.2               h29eaf8c_0    conda-forge
platformdirs              4.3.6                    pypi_0    pypi
plotly                    5.24.1                   pypi_0    pypi
prompt-toolkit            3.0.48                   pypi_0    pypi
protobuf                  5.29.1                   pypi_0    pypi
pthread-stubs             0.4               hb9d3cd8_1002    conda-forge
ptyprocess                0.7.0                    pypi_0    pypi
pure-eval                 0.2.3                    pypi_0    pypi
pybind11                  2.7.1                    pypi_0    pypi
pycparser                 2.22               pyh29332c3_1    conda-forge
pygments                  2.18.0                   pypi_0    pypi
pymeshlab                 2023.12.post2            pypi_0    pypi
pyparsing                 3.2.0                    pypi_0    pypi
pyquaternion              0.9.9                    pypi_0    pypi
pysocks                   1.7.1              pyha55dd90_7    conda-forge
python                    3.9.21          h9c0c6dc_1_cpython    conda-forge
python-dateutil           2.9.0.post0              pypi_0    pypi
python_abi                3.9                      5_cp39    conda-forge
pytorch                   1.13.1          py3.9_cuda11.7_cudnn8.5.0_0    pytorch
pytorch-cuda              11.7                 h778d358_5    pytorch
pytorch-mutex             1.0                        cuda    pytorch
pytz                      2024.2                   pypi_0    pypi
pyyaml                    6.0.2                    pypi_0    pypi
readline                  8.2                  h8228510_1    conda-forge
referencing               0.35.1                   pypi_0    pypi
requests                  2.32.3             pyhd8ed1ab_1    conda-forge
retrying                  1.3.4                    pypi_0    pypi
rpds-py                   0.22.3                   pypi_0    pypi
scikit-learn              1.6.0                    pypi_0    pypi
scipy                     1.13.1                   pypi_0    pypi
setuptools                75.6.0             pyhff2d567_1    conda-forge
six                       1.17.0                   pypi_0    pypi
stack-data                0.6.3                    pypi_0    pypi
svt-av1                   1.6.0                h59595ed_0    conda-forge
tenacity                  9.0.0                    pypi_0    pypi
tensorboard               2.18.0                   pypi_0    pypi
tensorboard-data-server   0.7.2                    pypi_0    pypi
threadpoolctl             3.5.0                    pypi_0    pypi
tk                        8.6.13          noxft_h4845f30_101    conda-forge
torchaudio                0.13.1               py39_cu117    pytorch
torchvision               0.14.1               py39_cu117    pytorch
tqdm                      4.62.3                   pypi_0    pypi
traitlets                 5.14.3                   pypi_0    pypi
trimesh                   4.5.3                    pypi_0    pypi
typing_extensions         4.12.2             pyha770c72_1    conda-forge
tzdata                    2024.2                   pypi_0    pypi
urllib3                   2.2.3              pyhd8ed1ab_1    conda-forge
wcwidth                   0.2.13                   pypi_0    pypi
werkzeug                  3.0.6                    pypi_0    pypi
wheel                     0.45.1             pyhd8ed1ab_1    conda-forge
widgetsnbextension        4.0.13                   pypi_0    pypi
x264                      1!164.3095           h166bdaf_2    conda-forge
x265                      3.5                  h924138e_3    conda-forge
xorg-fixesproto           5.0               hb9d3cd8_1003    conda-forge
xorg-kbproto              1.0.7             hb9d3cd8_1003    conda-forge
xorg-libice               1.1.2                hb9d3cd8_0    conda-forge
xorg-libsm                1.2.5                he73a12e_0    conda-forge
xorg-libx11               1.8.4                h0b41bf4_0    conda-forge
xorg-libxau               1.0.12               hb9d3cd8_0    conda-forge
xorg-libxdmcp             1.1.5                hb9d3cd8_0    conda-forge
xorg-libxext              1.3.4                h0b41bf4_2    conda-forge
xorg-libxfixes            5.0.3             h7f98852_1004    conda-forge
xorg-libxrender           0.9.10            h7f98852_1003    conda-forge
xorg-renderproto          0.11.1            hb9d3cd8_1003    conda-forge
xorg-xextproto            7.3.0             hb9d3cd8_1004    conda-forge
xorg-xproto               7.0.31            hb9d3cd8_1008    conda-forge
xz                        5.6.3                hbcc6ac9_1    conda-forge
xz-gpl-tools              5.6.3                hbcc6ac9_1    conda-forge
xz-tools                  5.6.3                hb9d3cd8_1    conda-forge
zipp                      3.21.0                   pypi_0    pypi
zlib                      1.3.1                hb9d3cd8_2    conda-forge
zstandard                 0.23.0           py39h08a7858_1    conda-forge
zstd                      1.5.6                ha6fb4c9_0    conda-forge
```

**Comment by AuthorityWang** [comment]
Hi, can you provide more details about the output log of NeuS2_K before `Error encountered while loading file:
"points3d.obj"`?

**Comment by TheOne-king** [comment]
I have met the same problem

**Comment by TheOne-king** [comment]
I have met the same problem


[Open3D WARNING] Unable to load file output\4k_actor2_dancing\neus2_output\0\points3d.obj with ASSIMP: Unable to open file "output\4k_actor2_dancing\neus2_output\0\points3d.obj".
Traceback (most recent call last):
  File "D:\Research\Project\3DGS\4DGS\VideoGS\train_sequence.py", line 75, in <module>
    ms.load_new_mesh(frame_neus2_mesh_output_path)
pymeshlab.pmeshlab.PyMeshLabException: Unable to open file: output/4k_actor2_dancing\neus2_output\0\points3d.obj
Error encountered while loading file:
"points3d.obj"

Error details: No vertex found

**Comment by qqx1221** [comment]
请问你生成point3d.obj的同时生成点云文件了吗

**Comment by TheOne-king** [comment]
> 请问你生成point3d.obj的同时生成点云文件了吗
没，output里就一个空的point3d.obj，不过这个问题似乎只在windows上出现，我重新在linux上部署，training就跑得通了

**Comment by TheOne-king** [comment]
I think I have figured out the problem, the output path should be the absolute path！

**Comment by asd56585452** [comment]
I have met the same problem

python train_sequence.py --start 0 --end 200 --cuda 0 --data /home/cgvmis418/VideoGS/datasets/4K_Actor1_Greeting_Preprocess --output /home/cgvmis418/VideoGS/output/4K_Actor1_Greeting_Preprocess --sh 0 --interval 1 --group_size 20 --resolution 2
0 200
0 19
create_directory:/home/cgvmis418/VideoGS/datasets/4K_Actor1_Greeting_Preprocess/0/output
create_directory: /home/cgvmis418/VideoGS/datasets/4K_Actor1_Greeting_Preprocess/0/output/mesh
create_directory: /home/cgvmis418/VideoGS/datasets/4K_Actor1_Greeting_Preprocess/0/output/images
founded json file: /home/cgvmis418/VideoGS/datasets/4K_Actor1_Greeting_Preprocess/0/transforms.json
total frame: 1
tmp_json_paths size: 1
10:46:32 INFO     Loading NeRF dataset from
10:46:32 INFO       /home/cgvmis418/VideoGS/datasets/4K_Actor1_Greeting_Preprocess/0/transforms.json
10:46:32 SUCCESS  Loaded 81 images after 0s
10:46:32 INFO       cam_aabb=[min=[-0.619845,-0.051681,-0.743291], max=[1.89367,1.04249,1.82284]]
10:46:32 INFO     Loading network config from: /home/cgvmis418/VideoGS/external/NeuS2_K/configs/nerf/base.json
m_predict_global_movement_training_step: 100
10:46:32 INFO     GridEncoding:  Nmin=16 b=1.45242 F=2 T=2^19 L=14
m_density_network_input_width: 32delta_network m_n_pos_dims: 6
accumulated transition params num: 4
******finish init accumulation parameters*****
10:46:32 INFO     Density model: 3--[HashGrid]-->28--[FullyFusedMLP(neurons=64,layers=3)]-->1
10:46:32 INFO     Color model:   3--[Composite]-->16+16--[FullyFusedMLP(neurons=64,layers=4)]-->3
{}
m_n_weights: 2048
m_n_weights_canonical: 2048
m_n_weights_delta: 0
10:46:32 INFO       total_encoding_params=10548128 total_network_params=11268
init m_network->n_params():10559396
[[0,["density_network",3072]],[1,["rgb_network",8192]],[2,["variance_network",4]],[3,["pos_encoding",10548128]],[4,["dir_encoding",0]]]
m_n_weights: 10559396
m_n_weights_canonical: 10559396
m_n_weights_delta: 0
initialize NeuS Network!
network_params_elements: 3072
m_variance_network_n_params: 4
{}
m_n_weights: 12
m_n_weights_canonical: 12
m_n_weights_delta: 0
transition_n_params:4
rotation_n_params:8
Training: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍| 1494/1500 [00:15<00:00, 96.09step/s, loss=0.000405]
Generating mesh via marching cubes and saving to /home/cgvmis418/VideoGS/output/4K_Actor1_Greeting_Preprocess/neus2_output/0/points3d.obj. Resolution=[500,500,500]
Segmentation fault (core dumped)
Traceback (most recent call last):
  File "/home/cgvmis418/VideoGS/train_sequence.py", line 73, in <module>
    ms.load_new_mesh(frame_neus2_mesh_output_path)
pymeshlab.pmeshlab.PyMeshLabException: Unable to open file: /home/cgvmis418/VideoGS/output/4K_Actor1_Greeting_Preprocess/neus2_output/0/points3d.obj
Error encountered while loading file:
"points3d.obj"

Error details: No vertex found

It seems that there is a problem in line 243 of /home/cgvmis418/VideoGS/external/NeuS2_K/scripts/run.py.
Has error: Segmentation fault (core dumped)

I use RTX 4090,cuda12.4 and pytorch 2.6.0

**Comment by TheOne-king** [comment]
> I have met the same problem
> 
> python train_sequence.py --start 0 --end 200 --cuda 0 --data /home/cgvmis418/VideoGS/datasets/4K_Actor1_Greeting_Preprocess --output /home/cgvmis418/VideoGS/output/4K_Actor1_Greeting_Preprocess --sh 0 --interval 1 --group_size 20 --resolution 2 0 200 0 19 create_directory:/home/cgvmis418/VideoGS/datasets/4K_Actor1_Greeting_Preprocess/0/output create_directory: /home/cgvmis418/VideoGS/datasets/4K_Actor1_Greeting_Preprocess/0/output/mesh create_directory: /home/cgvmis418/VideoGS/datasets/4K_Actor1_Greeting_Preprocess/0/output/images founded json file: /home/cgvmis418/VideoGS/datasets/4K_Actor1_Greeting_Preprocess/0/transforms.json total frame: 1 tmp_json_paths size: 1 10:46:32 INFO Loading NeRF dataset from 10:46:32 INFO /home/cgvmis418/VideoGS/datasets/4K_Actor1_Greeting_Preprocess/0/transforms.json 10:46:32 SUCCESS Loaded 81 images after 0s 10:46:32 INFO cam_aabb=[min=[-0.619845,-0.051681,-0.743291], max=[1.89367,1.04249,1.82284]] 10:46:32 INFO Loading network config from: /home/cgvmis418/VideoGS/external/NeuS2_K/configs/nerf/base.json m_predict_global_movement_training_step: 100 10:46:32 INFO GridEncoding: Nmin=16 b=1.45242 F=2 T=2^19 L=14 m_density_network_input_width: 32delta_network m_n_pos_dims: 6 accumulated transition params num: 4 *_**finish init accumulation parameters**_ 10:46:32 INFO Density model: 3--[HashGrid]-->28--[FullyFusedMLP(neurons=64,layers=3)]-->1 10:46:32 INFO Color model: 3--[Composite]-->16+16--[FullyFusedMLP(neurons=64,layers=4)]-->3 {} m_n_weights: 2048 m_n_weights_canonical: 2048 m_n_weights_delta: 0 10:46:32 INFO total_encoding_params=10548128 total_network_params=11268 init m_network->n_params():10559396 [[0,["density_network",3072]],[1,["rgb_network",8192]],[2,["variance_network",4]],[3,["pos_encoding",10548128]],[4,["dir_encoding",0]]] m_n_weights: 10559396 m_n_weights_canonical: 10559396 m_n_weights_delta: 0 initialize NeuS Network! network_params_elements: 3072 m_variance_network_n_params: 4 {} m_n_weights: 12 m_n_weights_canonical: 12 m_n_weights_delta: 0 transition_n_params:4 rotation_n_params:8 Training: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍| 1494/1500 [00:15<00:00, 96.09step/s, loss=0.000405] Generating mesh via marching cubes and saving to /home/cgvmis418/VideoGS/output/4K_Actor1_Greeting_Preprocess/neus2_output/0/points3d.obj. Resolution=[500,500,500] Segmentation fault (core dumped) Traceback (most recent call last): File "/home/cgvmis418/VideoGS/train_sequence.py", line 73, in ms.load_new_mesh(frame_neus2_mesh_output_path) pymeshlab.pmeshlab.PyMeshLabException: Unable to open file: /home/cgvmis418/VideoGS/output/4K_Actor1_Greeting_Preprocess/neus2_output/0/points3d.obj Error encountered while loading file: "points3d.obj"
> 
> Error details: No vertex found
> 
> It seems that there is a problem in line 243 of /home/cgvmis418/VideoGS/external/NeuS2_K/scripts/run.py. Has error: Segmentation fault (core dumped)
> 
> I use RTX 4090,cuda12.4 and pytorch 2.6.0

Have you successfully installed the modified NeuS2k provided by the author?

**Comment by asd56585452** [comment]
> > I have met the same problem
> > python train_sequence.py --start 0 --end 200 --cuda 0 --data /home/cgvmis418/VideoGS/datasets/4K_Actor1_Greeting_Preprocess --output /home/cgvmis418/VideoGS/output/4K_Actor1_Greeting_Preprocess --sh 0 --interval 1 --group_size 20 --resolution 2 0 200 0 19 create_directory:/home/cgvmis418/VideoGS/datasets/4K_Actor1_Greeting_Preprocess/0/output create_directory: /home/cgvmis418/VideoGS/datasets/4K_Actor1_Greeting_Preprocess/0/output/mesh create_directory: /home/cgvmis418/VideoGS/datasets/4K_Actor1_Greeting_Preprocess/0/output/images founded json file: /home/cgvmis418/VideoGS/datasets/4K_Actor1_Greeting_Preprocess/0/transforms.json total frame: 1 tmp_json_paths size: 1 10:46:32 INFO Loading NeRF dataset from 10:46:32 INFO /home/cgvmis418/VideoGS/datasets/4K_Actor1_Greeting_Preprocess/0/transforms.json 10:46:32 SUCCESS Loaded 81 images after 0s 10:46:32 INFO cam_aabb=[min=[-0.619845,-0.051681,-0.743291], max=[1.89367,1.04249,1.82284]] 10:46:32 INFO Loading network config from: /home/cgvmis418/VideoGS/external/NeuS2_K/configs/nerf/base.json m_predict_global_movement_training_step: 100 10:46:32 INFO GridEncoding: Nmin=16 b=1.45242 F=2 T=2^19 L=14 m_density_network_input_width: 32delta_network m_n_pos_dims: 6 accumulated transition params num: 4 *_**finish init accumulation parameters**_ 10:46:32 INFO Density model: 3--[HashGrid]-->28--[FullyFusedMLP(neurons=64,layers=3)]-->1 10:46:32 INFO Color model: 3--[Composite]-->16+16--[FullyFusedMLP(neurons=64,layers=4)]-->3 {} m_n_weights: 2048 m_n_weights_canonical: 2048 m_n_weights_delta: 0 10:46:32 INFO total_encoding_params=10548128 total_network_params=11268 init m_network->n_params():10559396 [[0,["density_network",3072]],[1,["rgb_network",8192]],[2,["variance_network",4]],[3,["pos_encoding",10548128]],[4,["dir_encoding",0]]] m_n_weights: 10559396 m_n_weights_canonical: 10559396 m_n_weights_delta: 0 initialize NeuS Network! network_params_elements: 3072 m_variance_network_n_params: 4 {} m_n_weights: 12 m_n_weights_canonical: 12 m_n_weights_delta: 0 transition_n_params:4 rotation_n_params:8 Training: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍| 1494/1500 [00:15<00:00, 96.09step/s, loss=0.000405] Generating mesh via marching cubes and saving to /home/cgvmis418/VideoGS/output/4K_Actor1_Greeting_Preprocess/neus2_output/0/points3d.obj. Resolution=[500,500,500] Segmentation fault (core dumped) Traceback (most recent call last): File "/home/cgvmis418/VideoGS/train_sequence.py", line 73, in ms.load_new_mesh(frame_neus2_mesh_output_path) pymeshlab.pmeshlab.PyMeshLabException: Unable to open file: /home/cgvmis418/VideoGS/output/4K_Actor1_Greeting_Preprocess/neus2_output/0/points3d.obj Error encountered while loading file: "points3d.obj"
> > Error details: No vertex found
> > It seems that there is a problem in line 243 of /home/cgvmis418/VideoGS/external/NeuS2_K/scripts/run.py. Has error: Segmentation fault (core dumped)
> > I use RTX 4090,cuda12.4 and pytorch 2.6.0
> 
> Have you successfully installed the modified NeuS2k provided by the author?

I have solved it by lowering the pytorch version(2.4.1), thank you

**Comment by mjtmm** [comment]
> I think I have figured out the problem, the output path should be the absolute path！

我也遇到了output里就point3d.obj为空的问题,能举例说明一下absolute path是什么样子的吗？谢谢

**Comment by 3normousz** [comment]
> > I have met the same problem
> > python train_sequence.py --start 0 --end 200 --cuda 0 --data /home/cgvmis418/VideoGS/datasets/4K_Actor1_Greeting_Preprocess --output /home/cgvmis418/VideoGS/output/4K_Actor1_Greeting_Preprocess --sh 0 --interval 1 --group_size 20 --resolution 2 0 200 0 19 create_directory:/home/cgvmis418/VideoGS/datasets/4K_Actor1_Greeting_Preprocess/0/output create_directory: /home/cgvmis418/VideoGS/datasets/4K_Actor1_Greeting_Preprocess/0/output/mesh create_directory: /home/cgvmis418/VideoGS/datasets/4K_Actor1_Greeting_Preprocess/0/output/images founded json file: /home/cgvmis418/VideoGS/datasets/4K_Actor1_Greeting_Preprocess/0/transforms.json total frame: 1 tmp_json_paths size: 1 10:46:32 INFO Loading NeRF dataset from 10:46:32 INFO /home/cgvmis418/VideoGS/datasets/4K_Actor1_Greeting_Preprocess/0/transforms.json 10:46:32 SUCCESS Loaded 81 images after 0s 10:46:32 INFO cam_aabb=[min=[-0.619845,-0.051681,-0.743291], max=[1.89367,1.04249,1.82284]] 10:46:32 INFO Loading network config from: /home/cgvmis418/VideoGS/external/NeuS2_K/configs/nerf/base.json m_predict_global_movement_training_step: 100 10:46:32 INFO GridEncoding: Nmin=16 b=1.45242 F=2 T=2^19 L=14 m_density_network_input_width: 32delta_network m_n_pos_dims: 6 accumulated transition params num: 4 *_**finish init accumulation parameters**_ 10:46:32 INFO Density model: 3--[HashGrid]-->28--[FullyFusedMLP(neurons=64,layers=3)]-->1 10:46:32 INFO Color model: 3--[Composite]-->16+16--[FullyFusedMLP(neurons=64,layers=4)]-->3 {} m_n_weights: 2048 m_n_weights_canonical: 2048 m_n_weights_delta: 0 10:46:32 INFO total_encoding_params=10548128 total_network_params=11268 init m_network->n_params():10559396 [[0,["density_network",3072]],[1,["rgb_network",8192]],[2,["variance_network",4]],[3,["pos_encoding",10548128]],[4,["dir_encoding",0]]] m_n_weights: 10559396 m_n_weights_canonical: 10559396 m_n_weights_delta: 0 initialize NeuS Network! network_params_elements: 3072 m_variance_network_n_params: 4 {} m_n_weights: 12 m_n_weights_canonical: 12 m_n_weights_delta: 0 transition_n_params:4 rotation_n_params:8 Training: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍| 1494/1500 [00:15<00:00, 96.09step/s, loss=0.000405] Generating mesh via marching cubes and saving to /home/cgvmis418/VideoGS/output/4K_Actor1_Greeting_Preprocess/neus2_output/0/points3d.obj. Resolution=[500,500,500] Segmentation fault (core dumped) Traceback (most recent call last): File "/home/cgvmis418/VideoGS/train_sequence.py", line 73, in ms.load_new_mesh(frame_neus2_mesh_output_path) pymeshlab.pmeshlab.PyMeshLabException: Unable to open file: /home/cgvmis418/VideoGS/output/4K_Actor1_Greeting_Preprocess/neus2_output/0/points3d.obj Error encountered while loading file: "points3d.obj"
> > Error details: No vertex found
> > It seems that there is a problem in line 243 of /home/cgvmis418/VideoGS/external/NeuS2_K/scripts/run.py. Has error: Segmentation fault (core dumped)
> > I use RTX 4090,cuda12.4 and pytorch 2.6.0
> 
> Have you successfully installed the modified NeuS2k provided by the author?

How can I verify whether the modified version of NeuS2_K was installed successfully? The build process completes without any errors, but I'm still encountering the same issue mentioned in this thread (No vertex found).
For context, my environment is: CMake: 3.22.1, CUDA: 11.6, PyTorch: 1.13.1

**Comment by TheOne-king** [comment]
就是完整的路径从home开始

________________________________

**Comment by wjz1316** [comment]
@asd56585452 Can you provide a detail environment list.
 I see this same question `Segmentation fault (core dumped)`, and I  use RTX 4090, cuda12.1 and torch==2.4.1 torchvision==0.19.1 torchaudio==2.4.1

**Comment by tvkamara** [comment]
@wjz1316 and @asd56585452 did you ever fix this issue? I am facing the same problem even though I am using full paths and pytorch 2.4.1
```
Training: 100%|█████████████████████████████████████████████████████████████████████▉| 1499/1500 [00:23<00:00, 63.83step/s, loss=0.000503]
Generating mesh via marching cubes and saving to /home/teemu/research/VideoGS/output/4K_Actor2_Dancing_test/neus2_output/0/points3d.obj. Resolution=[500,500,500]
Segmentation fault (core dumped)
Traceback (most recent call last):
  File "/home/teemu/research/VideoGS/train_sequence.py", line 73, in <module>
    ms.load_new_mesh(frame_neus2_mesh_output_path)
pymeshlab.pmeshlab.PyMeshLabException: Unable to open file: ...
```

**Comment by 3normousz** [comment]
> [@wjz1316](https://github.com/wjz1316) and [@asd56585452](https://github.com/asd56585452) did you ever fix this issue? I am facing the same problem even though I am using full paths and pytorch 2.4.1
> 
> ```
> Training: 100%|█████████████████████████████████████████████████████████████████████▉| 1499/1500 [00:23<00:00, 63.83step/s, loss=0.000503]
> Generating mesh via marching cubes and saving to /home/teemu/research/VideoGS/output/4K_Actor2_Dancing_test/neus2_output/0/points3d.obj. Resolution=[500,500,500]
> Segmentation fault (core dumped)
> Traceback (most recent call last):
>   File "/home/teemu/research/VideoGS/train_sequence.py", line 73, in <module>
>     ms.load_new_mesh(frame_neus2_mesh_output_path)
> pymeshlab.pmeshlab.PyMeshLabException: Unable to open file: ...
> ```

Make sure that you pasted 'cameras.bin', 'images.bin', and 'images.txt. into the dataset/colmap/sparse/. Mine structure is like this

4K_Actor1_Greeting/
├─ colmap/
│  ├─ sprase/
│  │  ├─ 0/
│  │  │  ├─ cameras.bin
│  │  │  ├─ images.bin
│  │  │  ├─ images.txt
│  │  ├─ cameras.bin
│  │  ├─ images.bin
│  │  ├─ images.txt
├─ image_undistortion_white/
│  ├─ %d/
│  ├─ colmap/
├─ images_white/
│  ├─ %d/
│  ├─ transform.json

**Comment by Rajrup** [comment]
I faced the same issue of segmentation fault.
Used these versions of python packages, instead of latest ones: [requirements.txt](https://github.com/AuthorityWang/NeuS2_K/blob/main/requirements.txt)

I think the culprit is numpy >= 2. Open3D needs numpy < 2. I installed all the packages at the original versions, then recompiled Neus2_K. This solved the issue for me.
